import { Node, Edge } from '@xyflow/react';
import { TableNodeData } from '../components/db-designer/TableNode';

export class SQLGenerator {

    static generate(nodes: Node<TableNodeData>[], edges: Edge[]): string {
        let sql = '-- Generated by AI Builder Database Designer\n\n';

        // 1. Create Tables
        nodes.forEach(node => {
            const tableName = node.data.label;
            const columns = node.data.columns || [];

            sql += `CREATE TABLE IF NOT EXISTS public.${tableName} (\n`;

            // Generate valid SQL for each column
            const colDefs = columns.map(col => {
                let def = `  ${col.name} ${this.mapType(col.type)}`;
                if (col.isPrimaryKey) {
                    def += ' PRIMARY KEY';
                    if (col.type === 'uuid') {
                        def += ' DEFAULT uuid_generate_v4()';
                    }
                }
                return def;
            });

            // Ensure we have at least ID and created_at if the user didn't add them, 
            // OR strictly follow user design. For "Visual" designer, strictly following user design is better,
            // but for "User Experience", we might want to auto-inject if missing? 
            // Let's stick to strict generation based on what they see. 
            // The initial state has 'id' and 'created_at'.

            sql += colDefs.join(',\n');
            sql += `\n);\n\n`;

            // Enable RLS by default
            sql += `ALTER TABLE public.${tableName} ENABLE ROW LEVEL SECURITY;\n\n`;

            // Basic Policy
            sql += `CREATE POLICY "Enable all access for authenticated users" \n`;
            sql += `ON public.${tableName} FOR ALL USING (auth.role() = 'authenticated');\n\n`;
        });

        // 2. Create Relations (Foreign Keys)
        edges.forEach(edge => {
            // For simplicity, we assume relations are simple FKs
            const sourceNode = nodes.find(n => n.id === edge.source);
            const targetNode = nodes.find(n => n.id === edge.target);

            if (sourceNode && targetNode) {
                const sourceTable = sourceNode.data.label;
                const targetTable = targetNode.data.label;

                sql += `-- Relation: ${sourceTable} -> ${targetTable}\n`;
                // Add column to TARGET referencing SOURCE
                // Usually target is the "Many" side in a drag
                sql += `ALTER TABLE public.${targetTable} \n`;
                sql += `ADD COLUMN IF NOT EXISTS ${sourceTable}_id uuid REFERENCES public.${sourceTable}(id) ON DELETE CASCADE;\n\n`;
            }
        });

        return sql;
    }

    private static mapType(type: string): string {
        switch (type) {
            case 'uuid': return 'uuid';
            case 'text': return 'text';
            case 'integer': return 'integer';
            case 'boolean': return 'boolean';
            case 'timestamp': return 'TIMESTAMP WITH TIME ZONE DEFAULT timezone(\'utc\'::text, now())';
            case 'jsonb': return 'jsonb';
            default: return 'text';
        }
    }
}
